In [1]:
import numpy as np

# The Basic

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
a.ndim

1

In [7]:
# Get Shape
a.shape

(3,)

In [16]:
# Get Type
a.dtype

dtype('int32')

In [17]:
# Get Size
a.itemsize

4

In [18]:
# Get total size
a.nbytes

12

# Accessing/Changing specific elements, rows, columns, etc

In [20]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
# Get a specific element [r,c] , r=row, c=column 
a[1, 5]

13

In [25]:
# Get a specific element [r,c] , r=row, c=column 
a[1, -2]

13

In [26]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [28]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])